# environment.yml
name: msa_benchmark
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.10,<3.13
  - mafft>=7.520
  - muscle>=5.1.0
  - t-coffee>=13.45
  - viennarna>=2.5.1
  - numpy>=1.26.4
  - pandas>=2.2.1
  - openpyxl>=3.1.2
  - biopython>=1.83
  - psutil>=5.9.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - pytest>=8.0.0
